---
version: '3'
services:
  dev-zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_ADMIN_ENABLESERVER: "false"
      ZOOKEEPER_SERVERS: dev-zookeeper-1:22888:23888;dev-zookeeper-2:32888:33888;dev-zookeeper-3:42888:43888
    ports:
      - '22181:22181'
    extra_hosts:
      - "kafka-dev:127.0.0.1"
     
  dev-zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_ADMIN_ENABLESERVER: "false"
      ZOOKEEPER_SERVERS: dev-zookeeper-1:22888:23888;dev-zookeeper-2:32888:33888;dev-zookeeper-3:42888:43888
    ports:
      - '32181:32181'
    extra_hosts:
      - "kafka-dev:127.0.0.1"
     
  dev-zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_ADMIN_ENABLESERVER: "false"
      ZOOKEEPER_SERVERS: dev-zookeeper-1:22888:23888;dev-zookeeper-2:32888:33888;dev-zookeeper-3:42888:43888
    ports:
      - '42181:42181'
    extra_hosts:
      - "kafka-dev:127.0.0.1"

  dev-kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://dev-kafka-1:19092
    ports:
      - '19092:19092'
    restart: on-failure      
    extra_hosts:
      - "kafka-dev:127.0.0.1"
     
  dev-kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://dev-kafka-2:29092
    ports:
      - '29092:29092'
    restart: on-failure      
    extra_hosts:
      - "kafka-dev:127.0.0.1"

  dev-kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://dev-kafka-3:39092
    ports:
      - '39092:39092'
    restart: on-failure      
    extra_hosts:
      - "kafka-dev:127.0.0.1"
      
  dev-kafka-4:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://dev-kafka-4:49092
    ports:
      - '49092:49092'
    restart: on-failure      
    extra_hosts:
      - "kafka-dev:127.0.0.1"
      
  dev-kafka-5:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
    environment:
      KAFKA_BROKER_ID: 5
      KAFKA_ZOOKEEPER_CONNECT: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://dev-kafka-5:59092
    ports:
      - '59092:59092'
    restart: on-failure      
    extra_hosts:
      - "kafka-dev:127.0.0.1"
  
  
  dev-schema-registry-1:
    image: confluentinc/cp-schema-registry:5.5.0
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
      - dev-kafka-1
      - dev-kafka-2
      - dev-kafka-3
      - dev-kafka-4
      - dev-kafka-5 
    ports:
      - '18081:8081'      
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://dev-kafka-1:19092, PLAINTEXT://dev-kafka-2:29092, PLAINTEXT://dev-kafka-3:39092, PLAINTEXT://dev-kafka-4:49092, PLAINTEXT://dev-kafka-5:59092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      SCHEMA_REGISTRY_HOST_NAME: dev-schema-registry-1
      SCHEMA_REGISTRY_LISTENERS: http://dev-schema-registry-1:8081
      SCHEMA_REGISTRY_GROUP_ID: "dev-schema_reg-grp1"
      SCHEMA_REGISTRY_DEBUG: "false"
    extra_hosts:
      - "kafka-dev:127.0.0.1"
      
  dev-schema-registry-2:
    image: confluentinc/cp-schema-registry:5.5.0
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
      - dev-kafka-1
      - dev-kafka-2
      - dev-kafka-3
      - dev-kafka-4
      - dev-kafka-5  
      - dev-schema-registry-1
    restart: on-failure            
    ports:
      - '28081:8081'
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://dev-kafka-1:19092, PLAINTEXT://dev-kafka-2:29092, PLAINTEXT://dev-kafka-3:39092, PLAINTEXT://dev-kafka-4:49092, PLAINTEXT://dev-kafka-5:59092
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      SCHEMA_REGISTRY_HOST_NAME: dev-schema-registry-2
      SCHEMA_REGISTRY_LISTENERS: http://dev-schema-registry-2:8081
      SCHEMA_REGISTRY_GROUP_ID: "dev-schema_reg-grp1"
      SCHEMA_REGISTRY_DEBUG: "false"
    extra_hosts:
      - "kafka-dev:127.0.0.1"
      
  dev-rest-proxy-1:
    image: confluentinc/cp-kafka-rest:5.5.0
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
      - dev-kafka-1
      - dev-kafka-2
      - dev-kafka-3
      - dev-kafka-4
      - dev-kafka-5
      - dev-schema-registry-1
      - dev-schema-registry-2
    restart: on-failure      
    environment:
      KAFKA_REST_HOST_NAME: dev-rest-proxy-1
      KAFKA_REST_ZOOKEEPER_CONNECT: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      KAFKA_REST_LISTENERS: http://dev-rest-proxy-1:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://dev-schema-registry-1:8081
    extra_hosts:
      - "kafka-dev:127.0.0.1"
      
  dev-rest-proxy-2:
    image: confluentinc/cp-kafka-rest:5.5.0
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
      - dev-kafka-1
      - dev-kafka-2
      - dev-kafka-3
      - dev-kafka-4
      - dev-kafka-5
      - dev-schema-registry-1
      - dev-schema-registry-2
    restart: on-failure      
    environment:
      KAFKA_REST_HOST_NAME: dev-rest-proxy-2
      KAFKA_REST_ZOOKEEPER_CONNECT: dev-zookeeper-1:22181,dev-zookeeper-2:32181,dev-zookeeper-3:42181
      KAFKA_REST_LISTENERS: http://dev-rest-proxy-2:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://dev-schema-registry-2:8081
    extra_hosts:
      - "kafka-dev:127.0.0.1"
      
  dev-connect-1:
    image: confluentinc/cp-kafka-connect:5.5.0
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
      - dev-kafka-1
      - dev-kafka-2
      - dev-kafka-3
      - dev-kafka-4
      - dev-kafka-5
      - dev-schema-registry-1
      - dev-schema-registry-2
    restart: on-failure      
    environment:
      CONNECT_BOOTSTRAP_SERVERS: dev-kafka-1:19092,dev-kafka-2:29092,dev-kafka-3:39092,dev-kafka-4:49092,dev-kafka-5:59092
      CONNECT_REST_PORT: '28082' 
      CONNECT_GROUP_ID: 'dev-connect-gr'
      CONNECT_CONFIG_STORAGE_TOPIC: 'dev-connect-gr-config'
      CONNECT_OFFSET_STORAGE_TOPIC: 'dev-connect-gr-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'dev-connect-gr-status'
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "dev-connect-1"
      CONNECT_PLUGIN_PATH: /usr/share/java
    extra_hosts:
      - "kafka-dev:127.0.0.1"
      
  dev-connect-2:
    image: confluentinc/cp-kafka-connect:5.5.0
    depends_on:
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
      - dev-kafka-1
      - dev-kafka-2
      - dev-kafka-3
      - dev-kafka-4
      - dev-kafka-5
      - dev-schema-registry-1
      - dev-schema-registry-2
    restart: on-failure      
    environment:
      CONNECT_BOOTSTRAP_SERVERS: dev-kafka-1:19092,dev-kafka-2:29092,dev-kafka-3:39092,dev-kafka-4:49092,dev-kafka-5:59092
      CONNECT_REST_PORT: '28082' 
      CONNECT_GROUP_ID: 'dev-connect-gr'
      CONNECT_CONFIG_STORAGE_TOPIC: 'dev-connect-gr-config'
      CONNECT_OFFSET_STORAGE_TOPIC: 'dev-connect-gr-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'dev-connect-gr-status'
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "dev-connect-2"
      CONNECT_PLUGIN_PATH: /usr/share/java
    extra_hosts:
      - "kafka-dev:127.0.0.1"

  
  dev-control-1:   
    image: confluentinc/cp-enterprise-control-center:latest
    depends_on:
      - dev-kafka-1
      - dev-kafka-2
      - dev-kafka-3
      - dev-kafka-4
      - dev-kafka-5
      - dev-zookeeper-1
      - dev-zookeeper-2
      - dev-zookeeper-3
      - dev-rest-proxy-1
      - dev-schema-registry-1
      - dev-connect-1
      - dev-connect-2
      
    ports:
      - '19021:9021'
    restart: on-failure      
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: dev-kafka-1:19092,dev-kafka-2:29092,dev-kafka-3:39092,dev-kafka-4:49092,dev-kafka-5:59092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_DEV_CLUSTER: http://dev-connect-1:28082
    extra_hosts:
      - "kafka-dev:127.0.0.1"
